CREATE DATABASE IF NOT EXISTS SpeZet;

USE SpeZet;

CREATE TABLE GTime (IDEmployee INTEGER, DAct DATE, IDJob INTEGER, IDItem INTEGER, Duration FLOAT, Description VARCHAR(50), PRIMARY KEY (IDEmployee, IDJob, IDItem)) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE MEmpl (IDEmployee INTEGER NOT NULL, ShortName VARCHAR(10), Name VARCHAR(40), DBegin DATE, DEnd DATE, Directory VARCHAR(50), Mode VARCHAR(1), PartTime FLOAT, IDJob INTEGER,
PRIMARY KEY (DBegin, DEnd), FOREIGN KEY (IDEmployee) REFERENCES GTime(IDEmployee)) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE MOrder (IDOrder INTEGER NOT NULL, NrOrder INTEGER, OrderDesc VARCHAR(80), IDOwner INTEGER NOT NULL, Budget FLOAT, DBegin DATE,
DEnd DATE, Mode VARCHAR(1), ArtCost INTEGER, BaseRate INTEGER, BaseItem INTEGER, PRIMARY KEY (IDOrder, IDOwner), FOREIGN KEY (DBegin) REFERENCES MEmpl(DBegin) ON UPDATE CASCADE ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE TABLE MItem (IDItem INTEGER NOT NULL, IDOrder INTEGER NOT NULL, NrItem INTEGER, Item VARCHAR(40), IDRate INTEGER, Mode VARCHAR(1),
PRIMARY KEY (IDRate), FOREIGN KEY (IDOrder) REFERENCES MOrder(IDOrder)) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

CREATE INDEX ind_dend ON MEmpl(DEnd);
ALTER TABLE MOrder ADD FOREIGN KEY (DEnd) REFERENCES MEmpl(DEnd);

CREATE INDEX ind_iditem ON GTime(IDItem);
ALTER TABLE MItem ADD FOREIGN KEY (IDItem) REFERENCES GTime(IDItem);